from distutils.core import setup

from os import path

here = path.abspath(path.dirname(__file__))
with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    long_description = f.read()


setuptools_scm_template = """\
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control

version = '{version}'
"""

setup(
    name='hms_logger',
    use_scm_version={
        'write_to': 'hms_irc/version.py',
        'write_to_template': setuptools_scm_template,
    },
    packages=['hms_logger'],
    scripts=['bin/hms_logger'],

    url='https://github.com/haum/hms_logger',
    license='MIT',

    author='Romain Porte (MicroJoe)',
    author_email='microjoe@microjoe.org',

    description='HAUM’s logging microservice',
    long_description=long_description,

    classifiers = [
        'Development Status :: 3 - Alpha',

        'Intended Audience :: Developers',

        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],

    setup_requires=[
        'setuptools_scm'
    ],

    install_requires=['pika', 'hms_base>=2.0,<3', 'coloredlogs', 'pymongo'],

    entry_points={
        'console_scripts': [
            'hms_logger = hms_logger.main:main',
        ]
    },
)
